feat(Print Order): track delivery and invoice status
ParaLogicTech/textile pull request #10
Opened 2023-04-06 10:50 UTC by haiderk0987

2023-04-10 11:41 UTC, SaiFi0102 requested changes

2023-04-10 11:41 UTC, SaiFi0102 commented on digital_printing/digital_printing/doctype/print_order/print_order.py
> +	target_doc.taxes_and_charges = None
remove this block

2023-04-10 11:41 UTC, SaiFi0102 commented on digital_printing/digital_printing/doctype/print_order/print_order.js
> +				console.log(r)
Remove `console.log`

2023-04-10 11:41 UTC, SaiFi0102 commented on digital_printing/digital_printing/doctype/print_order/print_order.py
> +		frappe.msgprint(_("Work Order already created in Draft."))
Are you sure?

2023-04-10 11:41 UTC, SaiFi0102 commented on digital_printing/digital_printing/doctype/print_order/print_order.py
> +	target_doc.taxes_and_charges = None
remove this block

2023-04-11 08:43 UTC, haiderk0987 commented on digital_printing/digital_printing/doctype/print_order/print_order.py
> +		frappe.msgprint(_("Work Order already created in Draft."))
pretty much...

2023-04-11 19:03 UTC, SaiFi0102 approved these changes

2023-04-11 19:03 UTC, merged